version: "3.9"

services:
    go-app:
        container_name: go-app
        image: go-api-layers
        build: .
        ports:
            - "3001:3001"
        depends_on:
            - go_db
    go_db:
        container_name: go_db
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
